-- -------------------------------------------------------------
-- Tabla para Formularios Dinámicos
-- -------------------------------------------------------------

create table if not exists public.form_definitions (
  id bigint generated by default as identity primary key,
  convenio_type_id bigint references public.convenio_types(id) not null,
  version int not null default 1,
  active boolean default true,
  schema jsonb not null, -- Aquí vive la "receta" del formulario
  template_path text, -- Ruta al archivo .docx en Storage
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Asegurar que solo haya una versión activa por tipo de convenio
  unique(convenio_type_id, version)
);

-- Habilitar RLS
alter table public.form_definitions enable row level security;

-- Políticas: Todos pueden leer los formularios activos
create policy "Public read access to active forms" on public.form_definitions
  for select using (active = true);

-- Solo admins pueden editar (si implementamos editor visual)
create policy "Admins can edit forms" on public.form_definitions
  for all using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

-- -------------------------------------------------------------
-- Datos Iniciales: Migración del "Convenio Marco" (ID: 2)
-- -------------------------------------------------------------

insert into public.form_definitions (convenio_type_id, version, active, schema)
values (
  2, -- ID del Convenio Marco
  1,
  true,
  '{
    "steps": [
      {
        "id": "datos_entidad",
        "title": "Datos de la Entidad",
        "description": "Información de la entidad que firmará el convenio marco.",
        "icon": "BuildingIcon",
        "fields": [
          {
            "name": "nombre",
            "label": "Nombre de la Entidad",
            "type": "text",
            "placeholder": "Nombre completo de la entidad",
            "required": true,
            "validation": {
              "min": 3,
              "message": "El nombre debe tener al menos 3 caracteres"
            }
          },
          {
            "name": "tipo",
            "label": "Tipo de Entidad",
            "type": "text",
            "placeholder": "Ej: EMPRESA, FUNDACION, ONG",
            "required": true,
            "transform": "uppercase",
            "validation": {
              "min": 2,
              "pattern": "^[A-ZÁÉÍÓÚÜÑ ]+$",
              "message": "Solo letras mayúsculas"
            }
          },
          {
            "name": "domicilio",
            "label": "Dirección",
            "type": "text",
            "placeholder": "Dirección completa",
            "required": true,
            "validation": {
              "min": 5,
              "message": "La dirección debe tener al menos 5 caracteres"
            }
          },
          {
            "name": "ciudad",
            "label": "Ciudad",
            "type": "text",
            "placeholder": "Ciudad",
            "required": true,
            "validation": {
              "min": 2,
              "message": "La ciudad es requerida"
            }
          },
          {
            "name": "cuit",
            "label": "CUIT (sin guiones)",
            "type": "text",
            "placeholder": "xx-xxxxxxxx-x",
            "required": true,
            "validation": {
              "min": 11,
              "pattern": "^\\d+$",
              "message": "El CUIT debe tener 11 números sin guiones"
            }
          }
        ]
      },
      {
        "id": "datos_representante",
        "title": "Datos del Representante",
        "description": "Información del representante legal de la entidad.",
        "icon": "UserIcon",
        "fields": [
          {
            "name": "representanteNombre",
            "label": "Nombre Completo",
            "type": "text",
            "placeholder": "Nombre completo del representante",
            "required": true,
            "validation": {
              "min": 3,
              "message": "El nombre debe tener al menos 3 caracteres"
            }
          },
          {
            "name": "cargoRepresentante",
            "label": "Cargo",
            "type": "text",
            "placeholder": "Ej: Gerente, Director",
            "required": true,
            "validation": {
              "min": 2,
              "message": "El cargo es requerido"
            }
          },
          {
            "name": "representanteDni",
            "label": "DNI",
            "type": "text",
            "placeholder": "sin puntos",
            "required": true,
            "validation": {
              "min": 7,
              "max": 8,
              "pattern": "^\\d+$",
              "message": "El DNI debe tener entre 7 y 8 números"
            }
          }
        ]
      },
      {
        "id": "fechas",
        "title": "Fechas del Convenio",
        "description": "Información para la fecha de firma del convenio.",
        "icon": "CalendarIcon",
        "fields": [
          {
            "name": "mes",
            "label": "Mes de Firma",
            "type": "select",
            "options": ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
            "required": true
          },
          {
            "name": "dia",
            "label": "Día de Firma",
            "type": "dependent-select",
            "dependsOn": "mes",
            "required": true
          }
        ]
      }
    ]
  }'::jsonb
);
