-- -------------------------------------------------------------
-- Schema para Convenios UTN (Open Source)
-- Compatible con PostgreSQL (Supabase)
-- -------------------------------------------------------------

-- 1. Tipos de Convenios (Catálogo)
create table if not exists public.convenio_types (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar tipos por defecto
insert into public.convenio_types (id, name, description) values
  (1, 'Convenio Particular de Práctica Supervisada', 'Para alumnos individuales'),
  (2, 'Convenio Marco', 'Acuerdo general entre instituciones'),
  (3, 'Acuerdo de Colaboración', 'Colaboración específica'),
  (4, 'Convenio Específico', 'Detalles puntuales derivados de un marco'),
  (5, 'Convenio Marco Práctica Supervisada', 'Marco general para pasantías')
on conflict (id) do nothing;

-- 2. Perfiles de Usuario (Extiende la tabla auth.users de Supabase)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  avatar_url text,
  role text check (role in ('admin', 'reviewer', 'user')) default 'user',
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabla Principal de Convenios
create table if not exists public.convenios (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  status text default 'borrador' check (status in ('borrador', 'enviado', 'aprobado', 'rechazado', 'archivado')),
  user_id uuid references public.profiles(id),
  convenio_type_id bigint references public.convenio_types(id),
  form_data jsonb default '{}'::jsonb, -- Aquí se guardan los datos flexibles del formulario
  document_path text, -- URL o Path al archivo en Drive/Storage
  serial_number text -- Número de serie generado (ej: 2025-001)
);

-- 4. Tokens de Google (Para uso offline de Drive API)
create table if not exists public.google_oauth_tokens (
  user_id uuid references auth.users not null primary key,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Log de Actividad (Auditoría)
create table if not exists public.activity_log (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  convenio_id uuid references public.convenios(id),
  action text not null,
  status_from text,
  status_to text,
  metadata jsonb,
  ip_address text
);

-- 6. Políticas de Seguridad (RLS) - Ejemplo Básico
alter table public.profiles enable row level security;
alter table public.convenios enable row level security;
alter table public.google_oauth_tokens enable row level security;

-- Política: Los usuarios pueden ver sus propios convenios
create policy "Users can view own convenios" on public.convenios
  for select using (auth.uid() = user_id);

-- Política: Los admins pueden ver todo (requiere lógica adicional en Supabase o Service Role)
-- Nota: El Service Role Key saltea estas políticas.
